account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.log_in, name='log_in'),
    path('logout', views.log_out, name='log_out'),
    path('signup', views.sign_up, name='sign_up'),
    path('', views.profil, name='profil'),
]

files_exchange/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search_files, name='search_files'),
    path('<int:id_page>/', views.search_files, name='search_files'),
    # path('results/', views.result_files, name='result_files'),
    # path('results/<int:page>/', views.result_files, name='result_files'),
    path('moderation/', views.moderation_page, name='moderation_page'),
    path('upload/', views.upload_file, name='upload_file'),
    path('ajax/propose_school/', views.propose_school_name, name='propose_school'),
    path('<int:id_file>/<slug:title_file>/', views.one_file_page, name='one_file_page'),
    path('test_translate/', views.test_i18n, name='test_translate'),
]

school_archives/urls.py
from django.contrib import admin
from django.urls import path, include
from account import views
from files_exchange import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('files/', include('files_exchange.urls')),
    path('account/', include('account.urls')),
    path('', views.index),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

files_exchange/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from uuid import uuid4
from django.utils.translation import ugettext_lazy as _

class TypeSchool(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("School's type"))
    slug_title = models.SlugField(max_length=100, null=True)

    def __str__(self):
        return self.slug_title

    def save(self, *args, **kwargs):
        self.slug_title = slugify(self.title)
        self.title = self.title.capitalize()
        super(TypeSchool, self).save(*args, **kwargs)

class School(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("School's name"))
    slug_title = models.SlugField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True, verbose_name=_("School's City"))
    type = models.ForeignKey(TypeSchool, on_delete = models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name=_("Creation date"))
    nb_files = models.IntegerField(default=0)
    nb_promos = models.IntegerField(default=0)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.slug_title

    def save(self, *args, **kwargs):
        self.slug_title = slugify(self.title)
        self.title = self.title.capitalize()
        super(School, self).save(*args, **kwargs)

class Promo(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("Section"))
    slug_title = models.SlugField(max_length=100, null=True)
    type = models.ForeignKey(TypeSchool, on_delete = models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug_title = slugify(self.title)
        super(Promo, self).save(*args, **kwargs)

class Subject(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("Discipline"))
    slug_title = models.SlugField(max_length=100, null=True)

    def __str__(self):
        return _(self.title).capitalize()

    def save(self, *args, **kwargs):
        self.slug_title = slugify(self.title)
        super(Subject, self).save(*args, **kwargs)

def path_and_rename(instance, filename):
    ext = filename.split('.')[-1]
    # set filename as random string
    filename = '{}.{}'.format(uuid4().hex, ext)
    # return the whole path to the file
    path = 'archives/files/'
    return os.path.join(path, filename)

class FileHomework(models.Model):
    title = models.CharField(max_length=100, verbose_name=_("File's name"))
    slug_title = models.SlugField(max_length=100, null=True)
    comment = models.TextField(max_length=250, verbose_name=_("File's description"))
    school = models.ForeignKey(School, on_delete = models.CASCADE, verbose_name=_("School's name"))
    promo = models.ForeignKey(Promo, on_delete = models.CASCADE, verbose_name=_("Section"))
    subject = models.ForeignKey(Subject, on_delete = models.CASCADE, verbose_name=_("Discipline"))
    date = models.DateTimeField(default=timezone.now, verbose_name=_("Creation date"))
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_("File's author"))
    nb_views = models.IntegerField(default=0)
    file_pdf = models.FileField(upload_to=path_and_rename)
    status = models.IntegerField(default=0)

    class Meta:
        ordering = ['-nb_views']

    def __str__(self):
        if self.status == 1:
            return self.slug_title + ' (PUBLISHED)'
        return self.slug_title

    def save(self, *args, **kwargs):
        self.slug_title = slugify(self.title)
        super(FileHomework, self).save(*args, **kwargs)

class Moderation(models.Model):
    date = models.DateTimeField(default=timezone.now, verbose_name="creation date")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    filehomework = models.ForeignKey(FileHomework, on_delete=models.CASCADE)
    is_suitable = models.BooleanField(null=True)

    def __str__(self):
        opinion = ''
        if self.is_suitable:
            end = 'suitable'
        elif self.is_suitable is None:
            end = ' ...'
        elif not self.is_suitable:
            end = 'NOT suitable'
        return str(self.author)+' on '+str(self.filehomework)+' : '+end

files_exchange/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

def file_size(value): # add this to some file where you can import it from
    nb_mib = 5
    limit = nb_mib * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed {} MiB.'.format(nb_mib))

class SearchFilesForm(forms.ModelForm):
    school = forms.CharField(label=_("School"), max_length=100)
    page = forms.CharField(widget = forms.HiddenInput(), initial=1)
    class Meta:
        model = FileHomework
        fields = ('title', 'promo', 'subject')

    def __init__(self, *args, **kwargs):
        super(SearchFilesForm, self).__init__(*args, **kwargs)
        self.fields['title'].required = False

    def clean(self):
        cleaned_data = super(SearchFilesForm, self).clean()
        school_name = cleaned_data.get('school')

        if school_name:
            if not School.objects.filter(title=school_name).exists():
                self.add_error(
                    "school",
                    "The school must exist!"
                )

class UploadFileForm(forms.ModelForm):
    school = forms.CharField(label=_("School"), max_length=100)
    class Meta:
        model = FileHomework
        fields = ( 'file_pdf', 'title', 'promo', 'subject', 'comment')
        widgets = {
          'comment': forms.Textarea(attrs={'rows':4, 'cols':40}),
        }
    file_pdf = forms.FileField(required=False, validators=[file_size])

    def __init__(self, *args, **kwargs):
        super(UploadFileForm, self).__init__(*args, **kwargs)
        # self.fields['comment'].widget.attrs['placeholder'] = self.fields['email'].label or 'email@address.nl'

    def clean(self):
        cleaned_data = super(UploadFileForm, self).clean()
        file_pdf = cleaned_data.get('file_pdf')
        school_name = cleaned_data.get('school')

        if file_pdf:
            filename = file_pdf.name
            if not filename.endswith('.pdf'):
                self.add_error(
                    "file_pdf",
                    "The file must be a pdf!"
                )

        if school_name:
            if not School.objects.filter(title=school_name).exists():
                self.add_error(
                    "school",
                    "The school must exist!"
                )

        return cleaned_data
#
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ('title', 'comment', 'image', 'video')
#
# class PostLikeForm(forms.ModelForm):
#     class Meta:
#         model = PostLike
#         fields = ('rank',)
#
#     rank = forms.IntegerField(max_value=9, min_value=0)
#
# class PostCommentForm(forms.ModelForm):
#     class Meta:
#         model = PostComment
#         fields = ('content',)
#
#     content = forms.CharField(max_length=255, widget=forms.Textarea)

files_exchange/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.paginator import Paginator, EmptyPage
from datetime import datetime
from django.utils import timezone
from files_exchange.models import *
from files_exchange.forms import *
# from accounts.models import Profil
from random import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, permission_required
from django.http import JsonResponse
from django.db.models import Q
from math import *
from django.utils.translation import ugettext as _
from django.utils.translation import ungettext
from django.utils import translation

def test_i18n(request):
    # translation.activate('fr')
    nb_chats = 1
    couleur = "white"
    chaine = _("Hello the newcomers !")
    ip = _("Your IP is %s") % request.META['REMOTE_ADDR']
    infos = ungettext(
        "… and as far I know, you have %(nb)s %(col)s cat !",
        "… and as far I know, you have %(nb)s %(col)s cats !",
        nb_chats) % {'nb': nb_chats, 'col': _(couleur)}
    # Translators: This message informs the user about how many books he can borrow
    quota = _("3 books")
    langage = request.LANGUAGE_CODE

    return render(request, 'files_exchange/test_i18n.html', locals())

def human_readable_size(size, decimal_places=3):
    for unit in ['B','KiB','MiB','GiB','TiB']:
        if size < 1024.0:
            break
        size /= 1024.0
    return f"{size:.{decimal_places}f}{unit}"

def index(request):
    return redirect(reverse('search_files')+'1/')
    # return HttpResponse("Hello, world. You're at the polls index.")

def propose_school_name(request):
    school_short = request.GET.get('school_short', None)
    schools = School.objects.filter(Q(title__icontains=school_short) | Q(city__contains=school_short))[:5]
    school_names = list()
    for school in schools:
        if school.city:
            school_names.append(school.title+', '+school.city)
        else:
            school_names.append(school.title)
    data = {
        'schools': school_names
    }
    return JsonResponse(data)

def search_files(request, id_page=0):
    if id_page==0:
        return redirect(reverse('search_files')+'1/')

    if request.method == 'POST':
        form = SearchFilesForm(request.POST or None)
        print(form)
        if form.is_valid():
            print('valid')
            # return redirect(reverse('result_files'))
            school = School.objects.filter(title=form.cleaned_data['school'])[0]
            promo = form.cleaned_data['promo']
            subject = form.cleaned_data['subject']
            title = form.cleaned_data['title']
            if not title:
                files = FileHomework.objects.filter(school=school, promo=promo, subject=subject, status=1)
                if len(files) == 0:
                    files = FileHomework.objects.filter(promo=promo, subject=subject, status=1)
            else:
                files = FileHomework.objects.filter(school=school, promo=promo, subject=subject, title__icontains=title, status=1)
                if len(files) == 0:
                    files = FileHomework.objects.filter(school=school, promo=promo, subject=subject, status=1)
                if len(files) == 0:
                    files = FileHomework.objects.filter(title__icontains=title, status=1)
                if len(files) == 0:
                    files = FileHomework.objects.filter(promo=promo, subject=subject, status=1)

            # files = FileHomework.objects.all()

            for file in files:
                nb_bytes = os.path.getsize(file.file_pdf.path)
                file.size = human_readable_size(nb_bytes, decimal_places=1)

            paginator = Paginator(files, 10, orphans=5, allow_empty_first_page=True)
            nb_files = len(files)
            try:
                files = paginator.page(id_page)
            except EmptyPage:
                files = paginator.page(paginator.num_pages)

    else:
        form = SearchFilesForm()

    is_post = request.method == 'POST'
    is_form_valid = form.is_valid()
    return render(request, 'files_exchange/search_files.html', locals())
#
# def result_files(request, page=1):
#     return render(request, 'files_exchange/result_files.html', locals())

def one_file_page(request, id_file, title_file):
    file = get_object_or_404(FileHomework, id=id_file, slug_title=title_file)
    if file.status == 1:
        file.nb_views += 1
        file.save()
        nb_bytes = os.path.getsize(file.file_pdf.path)
        file.size = human_readable_size(nb_bytes, decimal_places=1)
    elif file.status == -1:
        return redirect(reverse('search_files'))
    is_published = file.status == 1
    return render(request, 'files_exchange/one_file_page.html', locals())

@login_required
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            file = form.save(commit=False)
            file.school = School.objects.filter(title=form.cleaned_data['school'])[0]
            file.author = request.user
            if request.user.groups.filter(name='moderators').exists():
                file.status = 1
            file.save()
            return redirect(reverse('profil'))
    else:
        form = UploadFileForm()

    return render(request, 'files_exchange/upload_file.html', locals())

@permission_required('files_exchange.add_moderation')
def moderation_page(request):
    if (request.method == 'POST') and (request.POST.get('opinion')):
        mode = Moderation.objects.filter(author=request.user, is_suitable__isnull=True).order_by('-date')[0]
        opinion = request.POST.get('opinion')
        print(opinion)
        mode.is_suitable = opinion
        mode.save()
        if Moderation.objects.filter(filehomework=mode.filehomework, is_suitable=True).count() >= 2:
            file = mode.filehomework
            file.status = 1
            file.save()
        elif Moderation.objects.filter(filehomework=mode.filehomework, is_suitable=False).count() >= 2:
            file = mode.filehomework
            file.status = -1
            file.save()
        return redirect(reverse('moderation_page'))
    else:
        files = FileHomework.objects.filter(status=0).exclude(author=request.user).exclude(moderation__author=request.user).order_by('date')
        if files.count() > 0:
            file = files[0]
        else:
            return redirect(reverse('search_files'))
        mode = Moderation.objects.create(author=request.user, filehomework=file)
    nb_bytes = os.path.getsize(file.file_pdf.path)
    file.size = human_readable_size(nb_bytes, decimal_places=1)
    return render(request, 'files_exchange/moderation_page.html', locals())

files_exchange/templates/files_exchange/moderation_page.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block navbarcolor %}is-warning{% endblock %}

{% block page_title %}{% trans "Moderation" %}{% endblock %}
{% block page_subtitle %}{% trans "Is this file suitable for publishing?" %}{% endblock %}

{% block main %}
<div class="section" id="search_results">
  <div class="columns is-centered is-multiline">
    <div class="column is-two-thirds file-container" data-url="{% url 'one_file_page' file.id file.slug_title %}">
      <div class="box">
        <div class="container m-md">
          <div class="title">{{file.title|title}}.pdf, {{file.size}}</div>
        </div>
        <div class="container m-md">
          <div class="tags">
            <span class="tag is-medium tag_custom">{{file.school.title|title}}</span>
            {% if file.school.city %}
            <span class="tag is-medium">{{file.school.city|title}}</span>
            {% endif %}
            <span class="tag is-medium">{{file.promo.title}}</span>
            <span class="tag is-medium">{{file.subject.title|title}}</span>
          </div>
        </div>
        <nav class="level is-mobile">
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">{% trans "View" %}{{file.nb_views|pluralize}}</p>
              <p class="subtitle">{{file.nb_views|intword}}</p>
            </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">{% trans "Date" %}</p>
              <p class="subtitle">{{file.date|naturalday:"DATE_FORMAT"|title}}</p>
            </div>
          </div>
        </nav>
        <div class="container m-md">
          <p>{{file.comment}}</p>
        </div>
      </div>
    </div>

    <div class="column is-two-thirds" id="preview_pdf">
      {# <a href="/static/js/ViewerJS/index.html#{{ MEDIA_URL }}{{file.file_pdf.name}}" class="button">Preview</a> #}
      <iframe src = "/static/js/ViewerJS/index.html#{{ MEDIA_URL }}{{file.file_pdf.name}}" width='566' height='800' allowfullscreen webkitallowfullscreen class="pdf_preview"></iframe>
    </div>

    <div class="column is-two-thirds box m-t-md" id="moderation_question">
      <form action="{% url 'moderation_page' %}" method="post" id="form_moderation">
        {% csrf_token %}
        <input type="hidden" name="opinion" value="" id="id_opinion">
        <div class="has-text-centered m-sm m-b-lg">
          <p class="is-size-3">{% trans "Is this file suitable for publishing?" %}</p>
        </div>
        <div class="buttons is-centered">
          <div class="field is-grouped">
            <p class="control">
              <button class="button is-success is-large bt_opinion" data-opinion="True">
                <span class="icon is-medium">
                  <i class="fas fa-check"></i>
                </span>
                <span>{% trans "Yes" %}</span>
              </button>
            </p>
            <p class="control">
              <button class="button is-danger is-large bt_opinion" data-opinion="False">
                <span>{% trans "No" %}</span>
                <span class="icon is-medium">
                  <i class="fas fa-times"></i>
                </span>
              </button>
            </p>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
var pdf_preview = document.getElementsByTagName('iframe')[0];
window.onload = function() {
  console.log(pdf_preview.offsetWidth);
  pdf_preview.style.height = pdf_preview.offsetWidth*1.4+'px';
}

const buttons = document.getElementsByClassName('bt_opinion');
const op_input = document.getElementById('id_opinion');
const form_mode = document.getElementById('form_moderation');
for (var i = 0; i < buttons.length; i++) {
  buttons[i].addEventListener('click', function(e) {
    e.preventDefault();
    op_input.value = this.getAttribute('data-opinion');
    console.log(op_input.value);
    form_mode.submit();
  });
}
</script>
{% endblock %}

files_exchange/templates/files_exchange/one_file_page.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block header_second %}{% endblock %}

{% block main %}
<div class="section" id="search_results">
  <div class="columns is-centered is-multiline">
    {% if is_published %}
    {% include "files_exchange/reusable/file_card.html.django" %}

    <div class="column is-two-thirds" id="download_bt">
      <a href='{{ MEDIA_URL }}{{file.file_pdf.name}}' download="{{file.slug_title}}-school-archives.pdf">
        <div class="box has-background-primary has-text-white has-text-weight-bold is-size-5">
          <div class="container has-text-centered">
            <span class="icon is-small">
                <i class="fas fa-file-download"></i>
              </span>
              <span>{% trans "Download for free this file" %}</span>
          </div>
        </div>
      </a>
    </div>

    <div class="column is-two-thirds" id="preview_pdf">
      {# <a href="/static/js/ViewerJS/index.html#{{ MEDIA_URL }}{{file.file_pdf.name}}" class="button">Preview</a> #}
      <iframe src = "/static/js/ViewerJS/index.html#{{ MEDIA_URL }}{{file.file_pdf.name}}" width='566' height='800' allowfullscreen webkitallowfullscreen class="pdf_preview"></iframe>
    </div>
    {% else %}
    <div class="column is-two-thirds box">
      <article class="message is-warning">
        <div class="message-header">
          <p>{% trans "Download for free this file" %}</p>
        </div>
        <div class="message-body">
          <p>{% trans "Download for free this file" %}</p>
        </div>
      </article>
    </div>
    {% endif %}

  </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
var pdf_preview = document.getElementsByTagName('iframe')[0];
window.onload = function() {
  console.log(pdf_preview.offsetWidth);
  pdf_preview.style.height = pdf_preview.offsetWidth*1.4+'px';
}
</script>
{% endblock %}

files_exchange/templates/files_exchange/test_i18n.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}

<p>
  Hello the newcomers !<br />
  {{ chaine }}
</p>
<p>
  {{ ip }} {{ infos }}
</p>

<h2>{% trans "Contact-us !" %}</h2>
<p>{% trans quota %}</p>
<p>{{langage}}</p>
{% trans "mathematics" %}
{% trans "french" %}
{% trans "life and earth sciences" %}
{% trans "physics and chemistry" %}
{% trans "english" %}
{% trans "spanish" %}
{% trans "german" %}
{% trans "philosophy" %}
{% trans "history and geography" %}
{% trans "economy" %}
{% endblock %}

files_exchange/templates/files_exchange/upload_file.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% load i18n %}

{% block page_title %}{% trans "Upload file" %}{% endblock %}
{% block page_subtitle %}{% trans "post a file to help people" %}{% endblock %}

{% block main %}

<div class="section" id="upload_form">
  <form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {# {{ form | crispy}} #}
    {# <input type="submit" value="upload" /> #}


    <div class="container m-b-lg">
      <div class="columns">
        <div class="column">
          <div id="file-js" class="file has-name is-large is-centered is-boxed">
            <label class="file-label">
              {# <input class="file-input" type="file" name="resume"> #}
              <input type="file" name="file_pdf" class="clearablefileinput file-input" required="" id="id_file_pdf">
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  {% trans "Choose a pdf file…" %}
                </span>
              </span>
              <span class="file-name">
                {% trans "No file uploaded" %}
              </span>
            </label>
          </div>
          {% if form.file_pdf.errors %}
            <div id="error_1_id_file_pdf" class="help is-danger has-text-centered">{{form.file_pdf.errors}}</div>
          {% endif %}
        </div>
      </div>

      <div class="columns">
        <div class="column">
          {{ form.title|as_crispy_field }}
        </div>
      </div>
      <div class="columns">
        <div class="column">
          {{ form.school|as_crispy_field }}
          <div class="dropdown" id="schools_propositions">
            <div class="dropdown-menu" id="dropdown-menu" role="menu">
              <div class="dropdown-content" id="schools_list">
              </div>
            </div>
          </div>
        </div>
        <div class="column">
          {{ form.subject|as_crispy_field }}
        </div>
        <div class="column">
          {{ form.promo|as_crispy_field }}
        </div>
      </div>
      <div class="columns">
        <div class="column">
          {{ form.comment|as_crispy_field }}
        </div>
      </div>
    </div>
    <div class="has-text-centered">
      <button type="submit" class="button is-primary is-centered is-large has-text-weight-bold is-size-5" id="upload_bt">{% trans "Upload" %}</button>
    </div>

  </form>
</div>

{% endblock %}

{% block js %}

<script type="text/javascript">
const school_input = document.getElementById('id_school');
school_input.addEventListener('keyup', function() {
  school_input.classList.remove('is-danger');
  school_input.classList.remove('is-success');
  var str = this.value;
  if (str.length >= 3) {

    $.ajax({
      url: "{% url 'propose_school' %}",
      data: {
        'school_short': str
      },
      dataType: 'json',
      success: function (data) {
        var schools = data.schools;
        var school_drop = document.getElementById('schools_propositions');
        if (schools.length > 0) {
          var list_schools = document.getElementById('schools_list');
          list_schools.innerHTML = '';
          for (var i = 0; i < schools.length; i++) {
            list_schools.innerHTML += '<a class="dropdown-item school_name_proposition">'+schools[i]+'</a>';
            if (i != (schools.length-1)) {
              list_schools.innerHTML += '<hr class="dropdown-divider">';
            }
          }
          school_drop.classList.add('is-active');
          school_input.classList.remove('is-danger');
          school_input.classList.add('is-success');
          propositions = document.getElementsByClassName('school_name_proposition')
          for (var i = 0; i < propositions.length; i++) {
            propositions[i].addEventListener('click', function() {
              school_input.value = this.innerHTML.split(',')[0];
              list_schools.innerHTML = '';
              school_drop.classList.remove('is-active');
            });
          }
        }else {
          school_drop.classList.remove('is-active');
          school_input.classList.add('is-danger');
          school_input.classList.remove('is-success');
        }
        // console.log(data.schools);
      }
    });
  }
});

form_search = document.getElementsByTagName('form')[0];
search_bt = document.getElementById('upload_bt');
form_search.addEventListener('submit', function(e) {
  search_bt.classList.add('is-loading');
});

const fileInput = document.querySelector('#file-js input[type=file]');
const fileContainer = document.getElementById('file-js');
const titleInput = document.getElementById('id_title');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#file-js .file-name');
      fileName.textContent = fileInput.files[0].name;
      var ext = fileInput.files[0].name.substr(fileInput.files[0].name.lastIndexOf('.') + 1);
      if (ext == 'pdf') {
        fileContainer.classList.add('is-success');
        fileContainer.classList.remove('is-danger');
        titleInput.value = fileInput.files[0].name.substring(0, fileInput.files[0].name.length-4);
        titleInput.select();
      }else {
        fileContainer.classList.add('is-danger');
        fileContainer.classList.remove('is-success');
      }
    }
  }
</script>

{% endblock %}